liip_imagine :
    filter_sets :
        datatable_picture :
            quality : 75
            filters :
                thumbnail: { size : [300, 50], mode : outbound }
        article_picture_admin :
            quality : 75
            filters :
                thumbnail: { size : [200, 150], mode : outbound }
