services:
    app.manager.log:
        class: AppBundle\Manager\LogManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@translator"

    app.manager.article:
        class: AppBundle\Manager\ArticleManager
        arguments:
            - "@request_stack"
            - "@knp_paginator"
            - "@doctrine.orm.entity_manager"

    app.manager.booking:
        class: AppBundle\Manager\BookingManager
        arguments:
            - "@phpexcel"
            - "@translator"
            - "@app.repository.user"

    app.manager.stock:
            class: AppBundle\Manager\StockManager
            arguments:
                - "@doctrine.orm.entity_manager"

