# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
imports:
    - { resource: twig.yml }
    - { resource: manager.yml }
    - { resource: listener.yml }
    - { resource: form.yml }

services:
