AppBundle\Entity\User:
    properties:
        lastName:
            - NotNull:
                message: form.user.last_name.not_null
        firstName:
            - NotNull:
                message: form.user.first_name.not_null
        birthdayDate:
            - Date:
                message: form.user.birthday_date.date
    getters:
        lower:
            - IsTrue:
                message: form.user.birthday_date.lower

AppBundle\Entity\EventType:
    properties:
        name:
            - NotNull:
                message: form.event_type.name.not_null

AppBundle\Entity\Event:
    properties:
        name:
            - NotNull:
                message: form.event.name.not_null
        location:
            - NotNull:
                message: form.event.location.not_null
        date:
            - DateTime:
                message: form.event.date.datetime

AppBundle\Entity\TicketCategory:
    properties:
        label:
            - NotNull:
                message: form.ticket_category.label.not_null

AppBundle\Entity\Stock:
    properties:
        quantity:
            - Type:
                type: integer
                message: form.stock.quantity.int

AppBundle\Entity\Article:
    properties:
        file:
            - File:
                maxSize: 5M
                mimeTypes: [application/pdf, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document]
                mimeTypesMessage: form.article.file.mime_type
        image:
            - File:
                maxSize: 1M
                mimeTypes: [image/jpeg, image/png, image/gif]
                mimeTypesMessage: form.article.image.mime_type
        content:
            - NotNull:
                message: form.article.content.not_null
        title:
            - NotNull:
                message: form.article.title.not_null

